export enum ActionTypes {
  START_LOADING = '@reviews/START_LOADING',
  FINISH_LOADING = '@reviews/FINISH_LOADING',
  SET_REVIEWS_BY_APP = '@reviews/SET_REVIEWS_BY_APP',
  SET_CURRENT_REVIEW = '@reviews/SET_CURRENT_REVIEW',
  SET_REVIEWS_SORTS = '@reviews/SET_REVIEWS_SORTS',
  CREATE_REVIEW = '@reviews/CREATE_REVIEW',
  UPDATE_REVIEW = '@reviews/UPDATE_REVIEW',
  DELETE_REVIEW = '@reviews/DELETE_REVIEW',
}
